- name: Install smatch build dependencies
  ansible.builtin.package:
    name:
      - libsqlite3-dev
      - libssl-dev
    state: present
  become: true

- name: Clone smatch repo
  ansible.builtin.git:
    repo: "{{ smatch_url }}"
    dest: "{{ smatch_root }}"
    version: "{{ smatch_revision | default(omit) }}"
    force: true

- name: Upload check_host_input-add-a-pattern patch to remote node
  ansible.builtin.copy:
    src: files/0001-Enable-check_host_input-pattern.patch
    dest: "{{ bkc_root }}/smatch.patch"
    mode: '0660'

- name: Check whether git committer identity is configured
  ansible.builtin.command: git config user.email  # noqa command-instead-of-module
  register: git_config
  ignore_errors: true
  changed_when: false

- name: Configure git committer identity if not set
  ansible.builtin.command: "{{ item }}"  # noqa command-instead-of-module
  with_items:
    - git config --global user.email "ansible@ansible.com"
    - git config --global user.name "Ansible"
  when: git_config.rc != 0

- name: Apply smatch patch
  ansible.builtin.command: git am "{{ bkc_root }}/smatch.patch"  # noqa command-instead-of-module
  args:
    chdir: "{{ smatch_root }}"
  changed_when: false

- name: Build smatch
  ansible.builtin.make:
    chdir: "{{ smatch_root }}"
    params:
      --jobs: "{{ ansible_processor_nproc }}"

- name: Delete patch file
  ansible.builtin.file:
    path: "{{ bkc_root }}/smatch.patch"
    state: absent
