- name: Clone peinfo repo
  git:
    repo: "{{ peinfo_url }}"
    dest: "{{ peinfo_root }}"
    version: "{{ peinfo_revision }}"
    force: yes

- name: Build peinfo
  make:
    chdir: "{{ peinfo_root }}"
    jobs: "{{ ansible_processor_nproc }}"