- name: Clone kAFL EDK2 repo
  git:
    repo: "{{ kafl_edk2_url }}"
    dest: "{{ kafl_edk2_root }}"
    version: "{{ kafl_edk2_version }}"
    force: yes

- name: Initialize submodules
  command: git submodule update --init --recursive
  args:
    chdir: "{{ kafl_edk2_root }}"

- name: Build BaseTools
  command: make -C BaseTools
  args:
    chdir: "{{ kafl_edk2_root }}"
