- name: Build BaseTools
  ansible.builtin.make:
    chdir: "{{ tdvf_root }}/BaseTools"
    params:
      --jobs: "{{ ansible_processor_nproc }}"

- name: Build TDVF
  ansible.builtin.shell: >
    source edksetup.sh --reconfig &&
    build -n $(nproc) -p OvmfPkg/OvmfPkgX64.dsc -t GCC5 -a X64 -D TDX_EMULATION_ENABLE=FALSE -D DEBUG_ON_SERIAL_PORT=TRUE
  args:
    executable: /bin/bash
    chdir: "{{ tdvf_root }}"
  changed_when: false

- name: Copy TDVF image
  ansible.builtin.copy:
    src: "{{ tdvf_root }}/Build/OvmfX64/DEBUG_GCC5/FV/OVMF.fd"
    dest: "{{ image_root }}/TDVF_hello.fd"