- name: Install TDVF build dependencies
  ansible.builtin.package:
    name:
      - nasm
      - iasl
      - uuid-dev
      - python
    state: present
  become: yes

- name: Clone TDVF repo
  ansible.builtin.git:
    repo: "{{ tdvf_url }}"
    dest: "{{ tdvf_root }}"
    version: "{{ tdvf_revision | default(omit) }}"
    depth: "{{ git_clone_depth | default(omit) }}"
    force: true

- name: Initialize submodules
  command: git submodule update --init --recursive
  args:
    chdir: "{{ tdvf_root }}"

- name: Import build tasks
  import_tasks: build.yml
  tags:
    - build
    - never