- name: Install TDVF build dependencies
  ansible.builtin.package:
    name:
      - nasm
      - iasl
      - uuid-dev
      - python
    state: present
  become: yes

- name: Clone TDVF repo
  ansible.builtin.git:
    repo: "{{ tdvf_url }}"
    dest: "{{ tdvf_root }}"
    version: "{{ tdvf_revision | default(omit) }}"
    depth: "{{ git_clone_depth | default(omit) }}"
    force: true

- name: Initialize submodules
  command: git submodule update --init --recursive
  args:
    chdir: "{{ tdvf_root }}"

- name: Upload Nyx host version patch to remote node
  copy:
    src: files/0001-Update-Nyx-host-version.patch
    dest: "{{ tdvf_root }}/tdvf.patch"

- name: Apply Nyx host version patch
  command: git am "{{ tdvf_root }}/tdvf.patch"
  args:
    chdir: "{{ tdvf_root }}"

- name: Delete patch file
  file:
    path: "{{ tdvf_root }}/tdvf.patch"
    state: absent

- name: Download TDVF SDV binary
  ansible.builtin.get_url:
    url: https://github.com/IntelLabs/kafl.edk2/releases/download/tdvf-sdv-v0.1/TDVF_sdv_1G.fd
    dest: "{{ image_root }}/TDVF_SDV.fd"
    checksum: sha256:12fb25c9338065fcfaac5311e0e72a0fcef7292bb4e470fe4af5d29aca1bba62
    mode: '0660'

- name: Import build tasks
  import_tasks: build.yml
  tags:
    - build
    - never