- name: Copy BKC TDX guest kernel config
  ansible.builtin.copy:
    src: "{{ playbook_dir | dirname }}/bkc/kafl/linux_kernel_tdx_guest.config"
    dest: "{{ guest_root }}/.config"
    mode: '0660'

- name: Enable Virtio harness
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: "{{ guest_root }}"
  with_items:
    - ./scripts/config -e CONFIG_TDX_FUZZ_KAFL
    - ./scripts/config -e CONFIG_TDX_FUZZ_HARNESS_DOINITCALLS_VIRTIO
  changed_when: false

- name: Build TDX guest kernel
  community.general.system.make:
    chdir: "{{ guest_root }}"
    jobs: "{{ ansible_processor_nproc }}"

- name: Copy TDX guest kernel image
  ansible.builtin.copy:
    src: "{{ guest_root }}/arch/x86_64/boot/bzImage"
    dest: "{{ install_root}}/bzImage"
