- name: Install linux kernel build dependencies
  ansible.builtin.package:
    name:
      - libelf-dev
      - libssl-dev
      - bc
      - flex
      - bison
    state: present
  become: true

- name: Clone linux-guest repo
  ansible.builtin.git:
    repo: "{{ guest_url }}"
    dest: "{{ guest_root }}"
    version: "{{ guest_revision | default(omit) }}"
    depth: "{{ git_clone_depth | default(omit) }}"
    force: true

- name: Prepare fuzzing build of TDX guest kernel
  ansible.builtin.import_tasks: build.yml
  tags:
    - guest_build
    - never
    - build
