- name: Create firmware images directory
  ansible.builtin.file:
    path: "{{ image_root }}"
    state: directory

- name: Link kAFL fuzz script
  ansible.builtin.file:
    src: "{{ install_root }}/bkc/kafl/fuzz.sh"
    dest: "{{ install_root }}/fuzz.sh"
    state: link

# - name: Get host kernel version
#   ansible.builtin.shell: >
#     uname -r
#   args:
#     executable: /bin/bash
#   register: host_kernel_version
  
# - name: Link host kernel initrd
#   ansible.builtin.file:
#     src: "/boot/initrd.img-{{ host_kernel_version.stdout }}"
#     dest: "{{ install_root }}/initrd.cpio.gz"
#     state: link