- hosts: all
  environment:
    http_proxy: "{{ proxy_env.http_proxy | default(lookup('env', 'HTTP_PROXY')) }}"
    https_proxy: "{{ proxy_env.https_proxy | default(lookup('env', 'HTTPS_PROXY')) }}"
  vars:
    install_root: "{{ playbook_dir | dirname if ansible_connection == 'local' else ansible_env.HOME + '/ccc'}}"
    bkc_root: "{{ install_root }}/tdx"
    kafl_root: "{{ install_root }}/kafl"
    target_root: "{{ install_root }}/targets"
    workdir_root: "{{ install_root }}/workdirs"
    tools_root: "{{ install_root }}/tools"

  pre_tasks:
    - name: APT update
      apt:
        update_cache: true
      become: true

  roles:
    - role: bkc
      tags:
        - bkc
    - role: tdvf
      tags:
        - tdvf
    - role: guest
      tags:
        - guest
    - role: smatch
      tags:
        - smatch
    - role: peinfo
      tags:
        - peinfo
    - role: ghidra
      tags:
        - ghidra

  post_tasks:
    - name: Copy bkc folder
      copy:
        src: "{{ playbook_dir }}/bkc"
        dest: "{{ bkc_root }}/"
      when: ansible_connection != 'local'

  post_tasks:
    - name: Install env file
      template:
        src: env.j2
        dest: "{{ install_root }}/env.sh"