- name: Check for previous EDK2 version
  ansible.builtin.stat:
    path: "{{ edk2_root }}"
  register: stat_edk2

- name: Clone EDK2 repo
  ansible.builtin.git:
    repo: "{{ edk2_url }}"
    dest: "{{ edk2_root }}"
    version: "{{ edk2_revision | default(omit) }}"
    depth: "{{ git_clone_depth | default(omit) }}"
    force: true

- name: Initialize submodules
  command: git submodule update --init --recursive
  args:
    chdir: "{{ edk2_root }}"

- name: Import build tasks
  import_tasks: build.yml
  tags:
    - build
    - build_tdvf
    - never